---
language: python

dist: xenial

python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: 3.6-dev
    - python: 3.7-dev
    - python: nightly

install:
  - pip install tox
  - pip install tox-travis
  - pip install codacy-coverage

script:
  - tox

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
